# Site settings
title: Backlist
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://backlist.cc" # the base hostname & protocol for your site
twitter_username: bcklst
github_username: backlist
email: info@backlist.cc

# Data
collections:
  - books
  - people

# Build settings
markdown: kramdown
